import { useAcademy } from "../context/AcademyContext";

export function AboutPage() {
  const { platform } = useAcademy();
  return (
    <div className="page about-page">
      <header className="page-header about-header"><p className="eyebrow">Scope before confidence</p><h1>About Nornyx—and the boundaries that matter</h1><p>Nornyx is a governance contract and controls system around an agentic target. It is not the target’s model, planner, framework, workflow engine, tool runtime, identity provider, or independent enforcement boundary.</p></header>
      <section className="does-grid"><article><p className="eyebrow">Nornyx does</p><h2>Declare, check, generate, bind, decide, validate</h2><ul><li>Express governed identities, capabilities, zones, policies, approvals, and evidence expectations in <code>.nyx</code>.</li><li>Check and compose contracts and profiles.</li><li>Generate controls and locks.</li><li>Return authorization decisions through supported interfaces.</li><li>Validate supplied evidence and bindings.</li></ul></article><article className="does-not"><p className="eyebrow">Nornyx does not</p><h2>Orchestrate, execute, authenticate, attest runtime truth</h2><ul><li>Choose a model or plan agent work.</li><li>Make every runtime path use a generated control.</li><li>Turn cooperative in-process enforcement into an unavoidable boundary.</li><li>Prove that a producer told the truth merely because evidence is intact.</li><li>Govern this academy simply because the academy demonstrates Nornyx.</li></ul></article></section>
      <section className="boundary-table-section"><div className="section-heading"><div><p className="eyebrow">Keep these distinctions explicit</p><h2>Similar words, different claims</h2></div></div><div className="comparison-table-wrap"><table><thead><tr><th scope="col">Distinction</th><th scope="col">What one side establishes</th><th scope="col">What still needs proof</th></tr></thead><tbody><tr><th scope="row">Declaration vs enforcement</th><td>The contract states an intended rule.</td><td>A control actually intercepts the relevant runtime path.</td></tr><tr><th scope="row">Decision vs prevention</th><td>An authorizer returned allow or deny.</td><td>The tool obeyed that decision before the side effect.</td></tr><tr><th scope="row">Refusal text vs counter</th><td>The application produced a refusal message.</td><td>Attempts and completions show whether the action ran.</td></tr><tr><th scope="row">Integrity vs completeness</th><td>Supplied bytes match a digest or lock.</td><td>All relevant events exist and their assertions are true.</td></tr><tr><th scope="row">Covered vs unobserved path</th><td>Evidence supports the named surface.</td><td>Bypass and alternative paths remain outside that claim.</td></tr></tbody></table></div></section>
      <section className="platform-card"><div><p className="eyebrow">Connected platform</p><h2>Compatibility and assurance ceiling</h2></div>{platform ? <dl className="field-list"><div><dt>Academy</dt><dd>{platform.academy_version}</dd></div><div><dt>Nornyx runtime</dt><dd>{platform.nornyx_runtime_version}</dd></div><div><dt>Audited main</dt><dd><code>{platform.nornyx_audited_main_commit}</code></dd></div><div><dt>Main delta</dt><dd>{platform.nornyx_main_delta}</dd></div><div><dt>Adapter / SPI</dt><dd>{platform.adapter_version} / {platform.spi_version}</dd></div><div><dt>Assurance ceiling</dt><dd>{platform.assurance_tier_ceiling}</dd></div></dl> : <p>Connect the local academy service to inspect exact runtime and audited-source compatibility.</p>}</section>
      <section className="honest-statement"><p className="eyebrow">Academy assurance statement</p><h2>This is a training platform with inert default effects.</h2><p>Its demonstrations can support scoped claims about named, cooperative in-process surfaces when returned counters and evidence are complete. Unknown paths remain unknown. Nothing in this interface upgrades Tier 2 coverage to independent, unavoidable Tier 3 enforcement.</p></section>
    </div>
  );
}

