"""Generate docs/LAB_MIGRATION_MATRIX.md from authoritative sources.

Every field is derived, never hand-typed, so the matrix cannot drift away from
what the repository actually contains:

    labs/*/lab.toml      original title, concepts, chapters
    labs/*/checks.py     the original executable behaviour, and the tests that
                         are still preserved as engineering regressions
    academy/content/modules.json   interaction, scenario, assessment, disposition
    academy/content/paths.json     which learning paths include the module
    frontend/src/App.tsx           the routes that actually exist

A lab that lost its module, scenario, assessment, or path membership shows up
here as a blank cell rather than quietly disappearing — which is the whole point
of the document.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from nornyx_lab.contract import write_text_lf  # noqa: E402
from nornyx_lab.engine import all_labs  # noqa: E402

CONTENT = ROOT / "src" / "nornyx_lab" / "academy" / "content"
BANNER = "<!-- generated by scripts/build_migration_matrix.py — do not edit by hand -->"

# Interactions that own a dedicated top-level route. Everything else is taught
# inside the module lesson route.
DEDICATED_ROUTES = {
    "contract-workbench": "/workbench",
    "guided-contract-builder": "/builder",
    "trust-zone-graph": "/graph",
    "approval-simulator": "/approvals",
    "evidence-explorer": "/evidence",
    "diagnostics-viewer": "/diagnostics",
    "capstone-workspace": "/capstone",
    "contract-explorer": "/contracts",
}


def _routes() -> set[str]:
    app = (ROOT / "frontend" / "src" / "App.tsx").read_text(encoding="utf-8")
    return {"/" + m for m in re.findall(r'path="([^"*][^"]*)"', app)}


def _checks(lab_dir: Path) -> list[str]:
    path = lab_dir / "checks.py"
    if not path.is_file():
        return []
    return re.findall(r"^def (test_\w+)", path.read_text(encoding="utf-8"), re.M)


def _route_for(module_id: str, interaction: str, known: set[str]) -> str:
    dedicated = DEDICATED_ROUTES.get(interaction)
    if dedicated and dedicated in known:
        return f"`{dedicated}` + `/lessons/{module_id}`"
    return f"`/lessons/{module_id}`"


def main() -> int:
    modules = json.loads((CONTENT / "modules.json").read_text(encoding="utf-8"))
    paths = json.loads((CONTENT / "paths.json").read_text(encoding="utf-8"))
    assessments = json.loads((CONTENT / "assessments.json").read_text(encoding="utf-8"))
    lab_modules = modules["labs"]
    known_routes = _routes()

    assessment_ids = (
        set(assessments) if isinstance(assessments, dict) else {a.get("id") for a in assessments}
    )

    path_titles = {p["id"]: p["title"] for p in paths}
    membership: dict[str, list[str]] = {}
    for p in paths:
        for module_id in p["module_ids"]:
            membership.setdefault(module_id, []).append(p["id"])

    labs = all_labs()
    lines = [
        BANNER,
        "",
        "# Lab migration matrix",
        "",
        f"Every one of the {len(labs)} original labs, and what became of it.",
        "",
        "No lab was deleted. Each row states its disposition, where a learner now",
        "meets the material in the browser, and which of the original executable",
        "checks are still enforced as engineering regressions.",
        "",
        "**Disposition vocabulary**",
        "",
        "- **adapt for GUI** — the lab's executable behaviour is reachable through a",
        "  browser interaction; the terminal narration is gone.",
        "- **migrate and expand** — the GUI version teaches strictly more than the",
        "  original lab did.",
        "- **combine** — folded into a broader interactive module.",
        "- **superseded** — replaced by a stronger equivalent, named in the row.",
        "- **developer regression only** — no learner-facing GUI surface; retained",
        "  because the test encodes behaviour worth protecting.",
        "",
        "Original `checks.py` files are **engineering regressions**, not learner",
        "assessments. Learner completion requires a successful executable interaction",
        "*and* a scored GUI assessment.",
        "",
        "## Matrix",
        "",
    ]

    for meta in labs:
        module = lab_modules.get(meta.id)
        checks = _checks(meta.path)
        member_paths = membership.get(meta.id, [])

        if module is None:
            lines += [
                f"### Lab {meta.id} — {meta.title}",
                "",
                "> **UNMAPPED.** No academy module claims this lab. This is a defect,",
                "> not a disposition.",
                "",
            ]
            continue

        interaction = module.get("interaction", "")
        scenario = module.get("scenario_id", "")
        assessment = module.get("assessment_id", "")
        assessment_ok = assessment in assessment_ids
        route = _route_for(meta.id, interaction, known_routes)

        lines += [
            f"### Lab {meta.id} — {meta.title}",
            "",
            "| | |",
            "|---|---|",
            f"| **Disposition** | {module.get('migration_classification', '—')} |",
            f"| **Textbook chapters** | {meta.chapters} |",
            f"| **Original concepts** | {', '.join(f'`{c}`' for c in meta.concepts)} |",
            f"| **Original executable behaviour** | {len(checks)} check(s): "
            + ", ".join(f"`{c.removeprefix('test_')}`" for c in checks[:4])
            + (f", +{len(checks) - 4} more" if len(checks) > 4 else "")
            + " |",
            "| **Destination learning paths** | "
            + (", ".join(path_titles[p].split(":")[0] for p in member_paths) or "—")
            + " |",
            f"| **Destination GUI route** | {route} |",
            f"| **Interaction** | `{interaction or '—'}` |",
            f"| **Scenario mapping** | `{scenario or '—'}` |",
            f"| **Assessment mapping** | `{assessment or '—'}`"
            + ("" if assessment_ok else " — **MISSING from assessments.json**")
            + " |",
            f"| **Preserved tests** | `labs/{meta.slug}/checks.py` "
            + ("(kept as regression)" if checks else "(none)")
            + " |",
            f"| **What changed** | {module.get('summary', '—')} |",
            f"| **Why** | {module.get('why_it_matters', '—')} |",
            "",
        ]

    # ------------------------------------------------------------- integrity
    unmapped = [m.id for m in labs if m.id not in lab_modules]
    missing_assessment = [
        m.id
        for m in labs
        if m.id in lab_modules and lab_modules[m.id].get("assessment_id") not in assessment_ids
    ]
    orphan_paths = [m.id for m in labs if not membership.get(m.id)]

    lines += [
        "## Integrity",
        "",
        "These counts are computed at generation time. A non-zero entry is a defect.",
        "",
        f"- labs without an academy module: **{len(unmapped)}** {unmapped or ''}",
        f"- labs whose assessment id is absent: **{len(missing_assessment)}** {missing_assessment or ''}",
        f"- labs in no learning path: **{len(orphan_paths)}** {orphan_paths or ''}",
        f"- labs total: **{len(labs)}** · academy modules for labs: **{len(lab_modules)}**",
        "",
        "## Foundation modules added",
        "",
        "The original sequence assumed AI and software-engineering knowledge the new",
        "audiences do not have. These modules are new, not migrated:",
        "",
    ]
    foundations = modules["foundations"]
    items = (
        foundations.items()
        if isinstance(foundations, dict)
        else ((m.get("id", "?"), m) for m in foundations)
    )
    for module_id, module in items:
        lines.append(f"- **{module_id}** — {module.get('summary', '')}")
    lines.append("")

    write_text_lf(ROOT / "docs" / "LAB_MIGRATION_MATRIX.md", "\n".join(lines))
    print(f"Wrote docs/LAB_MIGRATION_MATRIX.md for {len(labs)} labs")
    print(
        f"  unmapped={len(unmapped)} missing_assessment={len(missing_assessment)} "
        f"orphan_paths={len(orphan_paths)}"
    )
    return 1 if (unmapped or missing_assessment or orphan_paths) else 0


if __name__ == "__main__":
    raise SystemExit(main())
