"""Generate the per-lab READMEs, the coverage matrix, and the concept index.

These are DERIVED artifacts (Lab 01's lesson, applied to this repository): each
one is a projection of `labs/*/lab.toml` plus the lab's own docstring. Edit the
source, not the output — `make check` in CI regenerates and byte-compares.
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from nornyx_lab.engine import LabMeta, all_labs  # noqa: E402

BANNER = "<!-- generated by scripts/build_docs.py — edit lab.toml, not this file -->"


def _lab_summary(meta: LabMeta) -> str:
    """The module docstring of lab.py, minus its title line."""
    lab_py = meta.path / "lab.py"
    if not lab_py.is_file():
        return ""
    try:
        tree = ast.parse(lab_py.read_text(encoding="utf-8"))
    except SyntaxError:
        return ""
    doc = ast.get_docstring(tree) or ""
    body = doc.split("\n", 1)[1].strip() if "\n" in doc else ""
    return re.sub(r"\n{3,}", "\n\n", body)


def _sections(meta: LabMeta) -> list[str]:
    """The `ctx.section(...)` headings, in order — the lab's actual outline."""
    lab_py = meta.path / "lab.py"
    if not lab_py.is_file():
        return []
    return re.findall(
        r'ctx\.section\(\s*\n?\s*["\'](.+?)["\']\s*\)', lab_py.read_text(encoding="utf-8")
    )


def _checks(meta: LabMeta) -> list[str]:
    """The propositions this lab's checks establish."""
    checks = meta.path / "checks.py"
    if not checks.is_file():
        return []
    names = re.findall(r"^def (test_\w+)", checks.read_text(encoding="utf-8"), re.M)
    return [n.removeprefix("test_").replace("_", " ") for n in names]


def lab_readme(meta: LabMeta) -> str:
    labs = all_labs()
    index = [m.id for m in labs].index(meta.id)
    previous = labs[index - 1] if index else None
    following = labs[index + 1] if index + 1 < len(labs) else None

    lines = [
        BANNER,
        "",
        f"# Lab {meta.id} — {meta.title}",
        "",
        f"**{meta.part}**  ",
        f"*{meta.chapters}*",
        "",
        f"`{meta.difficulty}` · about {meta.minutes} minutes",
        "",
        "```bash",
        f"nornyx-lab run {meta.id}      # run it",
        f"nornyx-lab check {meta.id}    # prove you got it",
        "```",
        "",
    ]

    summary = _lab_summary(meta)
    if summary:
        lines += [summary, ""]

    lines += ["## By the end of this lab you will be able to", ""]
    lines += [f"- {objective}" for objective in meta.objectives]
    lines += [""]

    sections = _sections(meta)
    if sections:
        lines += ["## What the lab does, in order", ""]
        lines += [f"{n}. {s}" for n, s in enumerate(sections, 1)]
        lines += [""]

    checks = _checks(meta)
    if checks:
        lines += [
            "## What `check` proves",
            "",
            "Each item is one proposition, written so a machine can settle it.",
            "That is the habit the whole book teaches: a governance claim you",
            "cannot express as a test is not yet a claim.",
            "",
        ]
        lines += [f"- {c}" for c in checks]
        lines += [""]

    lines += ["## Concepts introduced", ""]
    lines += [f"- `{concept}`" for concept in meta.concepts]
    lines += [""]

    if meta.path.joinpath("contract").is_dir() or meta.id >= "04":
        lines += [
            "## Files",
            "",
            f"- [`lab.py`]({'lab.py'}) — the runnable lab. Read it; it is the lesson.",
            f"- [`checks.py`]({'checks.py'}) — the propositions above, as tests.",
            "- [`lab.toml`](lab.toml) — metadata, objectives, chapter mapping.",
            "",
        ]

    nav = []
    if previous:
        nav.append(f"← [Lab {previous.id} — {previous.title}](../{previous.slug}/README.md)")
    nav.append("[All labs](../../README.md)")
    if following:
        nav.append(f"[Lab {following.id} — {following.title}](../{following.slug}/README.md) →")
    lines += ["---", "", " · ".join(nav), ""]

    return "\n".join(lines)


def coverage_matrix() -> str:
    lines = [
        BANNER,
        "",
        "# Coverage matrix",
        "",
        "Every chapter of *Governed Agentic Systems* maps to a lab. Chapters that",
        "share a mechanism are taught in one lab rather than repeated.",
        "",
        "| Lab | Title | Textbook chapters |",
        "|---|---|---|",
    ]
    part = None
    for meta in all_labs():
        if meta.part != part:
            part = meta.part
            lines.append(f"| | **{part}** | |")
        link = f"[`{meta.id}`](../labs/{meta.slug}/README.md)"
        lines.append(f"| {link} | {meta.title} | {meta.chapters} |")

    lines += [
        "",
        "## Chapter → lab",
        "",
        "| Chapters | Lab |",
        "|---|---|",
    ]
    for meta in all_labs():
        for chapter in re.findall(r"Ch\. (\d+)", meta.chapters):
            lines.append(f"| {chapter} | {meta.id} — {meta.title} |")

    covered = sorted(
        {int(c) for meta in all_labs() for c in re.findall(r"Ch\. (\d+)", meta.chapters)}
    )
    missing = [c for c in range(1, 42) if c not in covered]
    lines += [
        "",
        f"**{len(covered)} of 41 chapters mapped.**",
        "",
        f"Unmapped: {missing if missing else 'none'}",
        "",
    ]
    return "\n".join(lines)


def concept_index() -> str:
    lines = [
        BANNER,
        "",
        "# Concept index",
        "",
        "Where each concept is introduced. Run `nornyx-lab concepts` for the same",
        "list in your terminal.",
        "",
        "| Concept | Introduced in |",
        "|---|---|",
    ]
    seen: dict[str, LabMeta] = {}
    for meta in all_labs():
        for concept in meta.concepts:
            seen.setdefault(concept, meta)
    for concept, meta in sorted(seen.items()):
        lines.append(
            f"| `{concept}` | [Lab {meta.id} — {meta.title}](../labs/{meta.slug}/README.md) |"
        )
    lines += ["", f"**{len(seen)} concepts across {len(all_labs())} labs.**", ""]
    return "\n".join(lines)


def main() -> int:
    labs = all_labs()
    if not labs:
        print("no labs found")
        return 1

    for meta in labs:
        (meta.path / "README.md").write_text(lab_readme(meta), encoding="utf-8")

    docs = ROOT / "docs"
    docs.mkdir(exist_ok=True)
    (docs / "COVERAGE.md").write_text(coverage_matrix(), encoding="utf-8")
    (docs / "CONCEPTS.md").write_text(concept_index(), encoding="utf-8")

    print(f"Wrote {len(labs)} lab READMEs + docs/COVERAGE.md + docs/CONCEPTS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
