"""Live gateway→GitHub credential smoke test for H1-D provisioning.

``/health`` saying ``github_configured=true`` proves a token is *present*.
This script proves the deployed gateway can actually exercise the boundary
it was provisioned for, using its real production API and schema:

    synthetic session UUID
      → POST a valid synthetic payload through the deployed gateway
      → expect ``created``
      → independently fetch the resulting GitHub issue (operator authority,
        not the gateway's) and prove: intended intake repository, raw UUID
        absent, ``sha256(UUID)`` marker present, exactly one such issue
      → identical resubmit → ``unchanged``, same issue
      → one field changed, digest recomputed → ``updated``, same issue
      → close the synthetic issue

Any 401/403/404/422/5xx from the gateway, a duplicate creation, a wrong
repository, or an unidentifiable issue fails the run with a non-zero exit,
which aborts ``deploy_fly.sh`` before it can report the provisioning ready.

This is **not** H1-D learner acceptance: no consent flow, no learner UI, no
database-loss recovery, no revocation, and no change to the operational-claim
ratchet. It is only proof that the newly provisioned credential works.

Payloads are built from the committed golden Academy payload with a
stdlib-only canonicalisation (``sync`` dropped, keys sorted, compact
separators). A pre-flight recomputes the golden payload's own digest and
refuses to run on a mismatch, so canonicalisation drift is caught here
rather than as a confusing 422 from the gateway.

``--self-test`` drives the pass/fail logic with adversarial fixtures — an
unauthorized gateway reply, a write-key leak, a duplicate issue, a lost
issue, a wrong issue number — and requires every one to be rejected.

The session UUID is a write key even for a synthetic session, so it is
never printed; output identifies the session by its public marker prefix.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import urllib.error
import urllib.request
import uuid
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
GOLDEN = REPO_ROOT / "gateway" / "tests" / "academy_payload.golden.json"
LABEL = "learner-feedback"
DISCLAIMER = (
    "SYNTHETIC PROVISIONING SMOKE TEST - H1-D provisioning bootstrap. "
    "Generated by scripts/smoke_h1d_gateway.py. This is not human feedback."
)


class SmokeFailure(Exception):
    """One failed provisioning proof; the message says which and why."""


def require(condition: object, step: str, detail: str) -> None:
    if not condition:
        raise SmokeFailure(f"{step}: {detail}")


# --------------------------------------------------------------------------
# Payload construction — stdlib canonicalisation, digest recomputed


def canonical_digest(document: dict) -> str:
    body = {key: value for key, value in document.items() if key != "sync"}
    canonical = json.dumps(body, sort_keys=True, separators=(",", ":"))
    return "sha256:" + hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def preflight_digest_fidelity(golden: dict) -> None:
    """The committed golden payload is the cross-implementation contract."""

    require(
        canonical_digest(golden) == golden["sync"]["payload_digest"],
        "pre-flight",
        "stdlib canonicalisation no longer reproduces the golden payload digest - "
        "the payload model changed; update this script before provisioning",
    )


def build_synthetic_payload(golden: dict) -> tuple[dict, str, str]:
    document = json.loads(json.dumps(golden))  # deep copy
    write_key = str(uuid.uuid4())
    document["session"]["session_id"] = write_key
    document["module_feedback"][0]["perception"]["comment"] = DISCLAIMER
    document["course_feedback"]["perception"]["comments"] = DISCLAIMER
    document["sync"]["payload_digest"] = canonical_digest(document)
    marker = hashlib.sha256(write_key.encode("utf-8")).hexdigest()
    return document, write_key, marker


def mutate_one_field(document: dict) -> dict:
    changed = json.loads(json.dumps(document))
    perception = changed["module_feedback"][0]["perception"]
    perception["clarity"] = 5 if perception["clarity"] != 5 else 4
    changed["sync"]["payload_digest"] = canonical_digest(changed)
    return changed


# --------------------------------------------------------------------------
# Decision logic — pure, fixture-testable


def parse_sync_response(
    step: str,
    status: int,
    body_text: str,
    expect: str,
    expected_issue: int | None = None,
) -> int:
    """The gateway must answer 202 with the expected status word and issue."""

    require(
        status == 202,
        step,
        f"gateway answered HTTP {status}, not 202 - body: {body_text[:300]}",
    )
    try:
        body = json.loads(body_text)
    except json.JSONDecodeError:
        raise SmokeFailure(f"{step}: 202 body is not JSON") from None
    require(
        body.get("status") == expect,
        step,
        f"expected sync status {expect!r}, gateway said {body.get('status')!r}",
    )
    number = body.get("issue_number")
    require(isinstance(number, int) and number > 0, step, f"unusable issue_number {number!r}")
    if expected_issue is not None:
        require(
            number == expected_issue,
            step,
            f"issue moved: expected #{expected_issue}, gateway said #{number}",
        )
    return number


def find_unique_issue(step: str, listing: list[dict], marker: str) -> int:
    """Exactly one issue may carry the session's title fragment."""

    fragment = marker[:12]
    matches = [issue for issue in listing if fragment in issue.get("title", "")]
    require(
        len(matches) == 1,
        step,
        f"{len(matches)} issues carry marker fragment {fragment} - "
        + ("cannot identify the issue" if not matches else "duplicate creation"),
    )
    return matches[0]["number"]


def check_issue_privacy(step: str, issue: dict, write_key: str, marker: str) -> None:
    """The published issue must carry the marker and never the write key."""

    title = issue.get("title", "")
    body = issue.get("body", "")
    require(write_key not in title + body, step, "the raw session UUID reached the issue")
    require(marker[:12] in title, step, "issue title lacks the marker fragment")
    require(marker in body, step, "issue body lacks the full recovery marker")
    require(DISCLAIMER.split(" - ")[0] in body, step, "synthetic disclaimer missing from issue")
    labels = [label.get("name") for label in issue.get("labels", [])]
    require(LABEL in labels, step, f"label {LABEL!r} missing (labels: {labels})")


# --------------------------------------------------------------------------
# Transports


def post_feedback(endpoint: str, document: dict) -> tuple[int, str]:
    request = urllib.request.Request(
        endpoint.rstrip("/") + "/v1/feedback",
        data=json.dumps(document).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:  # noqa: S310
            return response.status, response.read().decode("utf-8")
    except urllib.error.HTTPError as error:
        return error.code, error.read().decode("utf-8", errors="replace")


class GithubViaGh:
    """Independent GitHub reads and the final close, through the gh CLI.

    Deliberately the operator's authority rather than the gateway's: the
    fetch that proves what reached GitHub must not depend on the credential
    under test.
    """

    def __init__(self, repository: str) -> None:
        self.repository = repository

    def _api(self, *arguments: str) -> dict | list:
        completed = subprocess.run(
            ["gh", "api", *arguments], capture_output=True, text=True, check=False
        )
        if completed.returncode != 0:
            raise SmokeFailure(f"gh api {arguments[0]} failed: {completed.stderr.strip()[:300]}")
        return json.loads(completed.stdout)

    def list_labelled(self) -> list[dict]:
        return self._api(f"repos/{self.repository}/issues?state=all&labels={LABEL}&per_page=100")

    def fetch(self, number: int) -> dict:
        return self._api(f"repos/{self.repository}/issues/{number}")

    def close(self, number: int, succeeded: bool) -> None:
        reason = "completed" if succeeded else "not_planned"
        self._api(
            "-X",
            "PATCH",
            f"repos/{self.repository}/issues/{number}",
            "-f",
            "state=closed",
            "-f",
            f"state_reason={reason}",
        )


class GithubViaMock:
    """Rehearsal-only transport for a local GitHub stand-in. Never production."""

    def __init__(self, repository: str, base: str, bearer: str) -> None:
        self.repository = repository
        self.base = base.rstrip("/")
        self.bearer = bearer

    def _request(self, method: str, path: str, payload: dict | None = None) -> dict | list:
        request = urllib.request.Request(
            self.base + path,
            data=None if payload is None else json.dumps(payload).encode("utf-8"),
            headers={"Authorization": f"Bearer {self.bearer}", "Content-Type": "application/json"},
            method=method,
        )
        with urllib.request.urlopen(request, timeout=10) as response:  # noqa: S310
            return json.loads(response.read())

    def list_labelled(self) -> list[dict]:
        return self._request(
            "GET", f"/repos/{self.repository}/issues?state=all&labels={LABEL}&per_page=100&page=1"
        )

    def fetch(self, number: int) -> dict:
        listing = self.list_labelled()
        for issue in listing:
            if issue.get("number") == number:
                return issue
        raise SmokeFailure(f"issue fetch: #{number} not found in mock listing")

    def close(self, number: int, succeeded: bool) -> None:
        self._request("PATCH", f"/repos/{self.repository}/issues/{number}", {"state": "closed"})


# --------------------------------------------------------------------------
# The smoke sequence


def run_smoke(endpoint: str, github: GithubViaGh | GithubViaMock, golden_path: Path) -> None:
    golden = json.loads(golden_path.read_text(encoding="utf-8"))
    preflight_digest_fidelity(golden)

    payload, write_key, marker = build_synthetic_payload(golden)
    print(f"synthetic session marker {marker[:12]}... (write key not printed)")

    issue: int | None = None
    succeeded = False
    try:
        status, body = post_feedback(endpoint, payload)
        issue = parse_sync_response("first synchronisation", status, body, "created")
        print(f"created issue #{issue}")

        found = find_unique_issue("issue identification", github.list_labelled(), marker)
        require(
            found == issue,
            "issue identification",
            f"gateway reported #{issue} but the marker matches #{found}",
        )
        check_issue_privacy("issue content", github.fetch(issue), write_key, marker)
        print(f"issue #{issue} verified in the intake repository: marker present, write key absent")

        status, body = post_feedback(endpoint, payload)
        parse_sync_response("identical resubmit", status, body, "unchanged", expected_issue=issue)
        print("identical resubmit: unchanged, same issue")

        status, body = post_feedback(endpoint, mutate_one_field(payload))
        parse_sync_response("changed resubmit", status, body, "updated", expected_issue=issue)
        check_issue_privacy("updated issue content", github.fetch(issue), write_key, marker)
        print("changed resubmit: updated, same issue, still no write key in the issue")

        succeeded = True
    finally:
        if issue is not None:
            github.close(issue, succeeded)
            print(
                f"synthetic issue #{issue} closed ({'completed' if succeeded else 'not_planned'})"
            )

    print("LIVE GATEWAY->GITHUB SMOKE PASSED")


# --------------------------------------------------------------------------
# Negative controls for the checker itself


def self_test() -> int:
    """Every rejection path must actually reject; a healthy run must pass."""

    write_key = str(uuid.uuid4())
    marker = hashlib.sha256(write_key.encode("utf-8")).hexdigest()
    good_issue = {
        "number": 7,
        "title": f"[Learner Feedback] Session {marker[:12]}",
        "body": f"<!-- nornyx-marker {marker} -->\nSYNTHETIC PROVISIONING SMOKE TEST body",
        "labels": [{"name": LABEL}],
    }
    created = json.dumps({"status": "created", "issue_number": 7})

    rejections: list[tuple[str, object]] = [
        (
            "unauthorized gateway reply (upstream 401 surfaced)",
            lambda: parse_sync_response("t", 503, json.dumps({"code": "github_error"}), "created"),
        ),
        (
            "raw 401 from the gateway",
            lambda: parse_sync_response("t", 401, "unauthorized", "created"),
        ),
        (
            "422 digest refusal",
            lambda: parse_sync_response(
                "t", 422, json.dumps({"code": "digest_mismatch"}), "created"
            ),
        ),
        (
            "first sync answered updated instead of created",
            lambda: parse_sync_response(
                "t", 202, json.dumps({"status": "updated", "issue_number": 7}), "created"
            ),
        ),
        (
            "issue moved between resubmits",
            lambda: parse_sync_response("t", 202, created, "created", expected_issue=6),
        ),
        (
            "write key leaked into the issue",
            lambda: check_issue_privacy(
                "t", {**good_issue, "body": good_issue["body"] + write_key}, write_key, marker
            ),
        ),
        (
            "marker missing from the issue",
            lambda: check_issue_privacy(
                "t",
                {
                    **good_issue,
                    "title": "[Learner Feedback] Session ffffffffffff",
                    "body": "no marker",
                },
                write_key,
                marker,
            ),
        ),
        (
            "duplicate creation (two issues carry the marker)",
            lambda: find_unique_issue("t", [good_issue, dict(good_issue)], marker),
        ),
        (
            "cannot identify the issue (empty listing)",
            lambda: find_unique_issue("t", [], marker),
        ),
    ]

    failures = 0
    for name, attack in rejections:
        try:
            attack()
        except SmokeFailure as verdict:
            print(f"[PASS] rejects {name}: {verdict}")
        else:
            print(f"[FAIL] checker ACCEPTED {name}")
            failures += 1

    try:
        number = parse_sync_response("healthy", 202, created, "created")
        assert find_unique_issue("healthy", [good_issue], marker) == number
        check_issue_privacy("healthy", good_issue, write_key, marker)
        parse_sync_response(
            "healthy",
            202,
            json.dumps({"status": "unchanged", "issue_number": 7}),
            "unchanged",
            expected_issue=7,
        )
        print("[PASS] healthy sequence accepted")
    except SmokeFailure as error:
        print(f"[FAIL] healthy sequence wrongly rejected: {error}")
        failures += 1

    print(f"{len(rejections) + 1 - failures}/{len(rejections) + 1} checker controls passed")
    return 1 if failures else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--self-test", action="store_true", help="run the checker's negative controls"
    )
    parser.add_argument("--endpoint", help="deployed gateway base URL")
    parser.add_argument("--repository", help="owner/name of the intake repository")
    parser.add_argument("--golden", type=Path, default=GOLDEN)
    parser.add_argument("--mock-issues-base", help="REHEARSAL ONLY: local GitHub stand-in base URL")
    parser.add_argument(
        "--mock-bearer", help="REHEARSAL ONLY: stand-in bearer value (not a secret)"
    )
    arguments = parser.parse_args(argv)

    if arguments.self_test:
        return self_test()
    if not arguments.endpoint or not arguments.repository:
        parser.error("--endpoint and --repository are required (or use --self-test)")

    if arguments.mock_issues_base:
        github: GithubViaGh | GithubViaMock = GithubViaMock(
            arguments.repository, arguments.mock_issues_base, arguments.mock_bearer or ""
        )
    else:
        github = GithubViaGh(arguments.repository)

    try:
        run_smoke(arguments.endpoint, github, arguments.golden)
    except SmokeFailure as failure:
        print(f"SMOKE FAILED - {failure}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
